"""
AEOS UI Evidence Pack — multi-file evidence bundle from MemoryRecords.

Read-only. No network. No AI. No secrets. No .env.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from html import escape
from pathlib import Path

from aeos.ui.dashboard import DashboardData, load_dashboard_data, render_dashboard
from aeos.ui.workspace import WorkspaceData, load_workspace_data, render_workspace

# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

_PACK_FILES = [
    "index.html",
    "dashboard.html",
    "project-workspace.html",
    "recovery-summary.md",
    "risk-register.md",
    "human-gates.md",
    "next-actions.md",
]


@dataclass
class EvidencePackResult:
    """Metadata about a generated evidence pack."""

    output_dir: Path
    project_name: str
    record_count: int
    verdict: str
    files: list[Path] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Markdown renderers
# ---------------------------------------------------------------------------


def _delta_str(delta: int) -> str:
    if delta == 0:
        return "unchanged"
    sign = "+" if delta > 0 else ""
    return f"{sign}{delta}"


def render_recovery_summary(ws: WorkspaceData) -> str:
    """Return recovery-summary.md as a string."""
    p = ws.recovery_progress
    pr = ws.production_readiness

    lines: list[str] = [
        f"# Recovery Summary — {ws.project_name}",
        "",
        f"**Date:** {p.last_date}",
        f"**Period:** {p.first_date} → {p.last_date}",
        f"**Audit records:** {p.record_count}",
        f"**Production verdict:** {pr.verdict}",
        "",
        "read_only: true · applied: false · human validation required",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        ws.executive_summary,
        "",
        "---",
        "",
        "## Initial State (Baseline)",
        "",
        "| Metric | Value |",
        "|--------|-------|",
    ]
    for key, label in [
        ("critical", "Critical findings"),
        ("important", "Important findings"),
        ("manual", "Manual actions"),
        ("generated", "Generatable SQL blocks"),
    ]:
        lines.append(f"| {label} | {p.baseline.get(key, 0)} |")

    lines += [
        "",
        "## Current State",
        "",
        "| Metric | Baseline | Current | Change |",
        "|--------|----------|---------|--------|",
    ]
    for key, label in [
        ("critical", "Critical findings"),
        ("important", "Important findings"),
        ("manual", "Manual actions"),
        ("generated", "Generatable SQL blocks"),
    ]:
        b = p.baseline.get(key, 0)
        c = p.current.get(key, 0)
        d = p.deltas.get(key, 0)
        lines.append(f"| {label} | {b} | {c} | {_delta_str(d)} |")

    lines += [
        "",
        "---",
        "",
        "## Production Readiness",
        "",
        f"**{pr.verdict}**",
        "",
    ]
    if pr.reasons:
        lines.append("Blocking reasons:")
        lines.append("")
        for r in pr.reasons:
            lines.append(f"- {r}")
    else:
        lines.append("No blocking reasons — all gates passed.")

    lines += ["", "---", "", "_Generated by AEOS Evidence Pack — read-only._"]
    return "\n".join(lines) + "\n"


def render_risk_register(ws: WorkspaceData) -> str:
    """Return risk-register.md as a string."""
    last = ws.records[-1]
    fs = last.findings_summary
    critical = fs.get("critical", 0)
    important = fs.get("important", 0)
    manual = fs.get("manual", 0)
    generated = fs.get("generated", 0)

    lines: list[str] = [
        f"# Risk Register — {ws.project_name}",
        "",
        f"**As of:** {ws.recovery_progress.last_date}",
        f"**Source:** last audit record `{last.record_id}`",
        "",
        "read_only: true · applied: false · human validation required",
        "",
        "---",
        "",
        "| Category | Count | Severity | Action required |",
        "|----------|-------|----------|-----------------|",
        (
            f"| Critical findings | {critical} | HIGH"
            " | Must be resolved before any production deployment |"
        ),
        (
            f"| Important findings | {important} | MEDIUM"
            " | Security, sovereignty, and RLS hardening |"
        ),
        (
            f"| Manual actions | {manual} | MEDIUM"
            " | Require explicit human decision and execution |"
        ),
        (
            f"| Generatable SQL blocks | {generated} | LOW"
            " | Auto-generated — require review before applying |"
        ),
        "",
        "---",
        "",
        "## Notes",
        "",
        "- **Critical:** findings that block production until explicitly resolved.",
        (
            "- **Important:** security or sovereignty findings;"
            " addressable in staged remediation."
        ),
        "- **Manual:** actions that cannot be automated — require CTO/lead approval.",
        (
            "- **Generatable SQL:** blocks computed by AEOS harden;"
            " must be reviewed then applied to staging."
        ),
        "",
        "---",
        "",
        "_Generated by AEOS Evidence Pack — read-only._",
    ]
    return "\n".join(lines) + "\n"


def render_human_gates(ws: WorkspaceData) -> str:
    """Return human-gates.md as a string."""
    lines: list[str] = [
        f"# Human Validation Gates — {ws.project_name}",
        "",
        f"**As of:** {ws.recovery_progress.last_date}",
        (
            "**Status:** all gates require explicit human approval"
            " before production deployment."
        ),
        "",
        "read_only: true · applied: false · human validation required",
        "",
        "---",
        "",
    ]
    if ws.human_gates:
        for i, gate in enumerate(ws.human_gates, start=1):
            lines += [
                f"## Gate {i}",
                "",
                f"○ {gate}",
                "",
                "- [ ] Validated by:",
                "- [ ] Date:",
                "- [ ] Notes:",
                "",
            ]
    else:
        lines += ["No open human gates.", ""]

    lines += [
        "---",
        "",
        (
            "_All gates must be explicitly checked and signed off"
            " before production deployment._"
        ),
        "",
        "_Generated by AEOS Evidence Pack — read-only._",
    ]
    return "\n".join(lines) + "\n"


def render_next_actions(ws: WorkspaceData) -> str:
    """Return next-actions.md as a string."""
    lines: list[str] = [
        f"# Next Recommended Actions — {ws.project_name}",
        "",
        f"**As of:** {ws.recovery_progress.last_date}",
        f"**Production verdict:** {ws.production_readiness.verdict}",
        "",
        "read_only: true · applied: false · human validation required",
        "",
        "---",
        "",
    ]
    for i, action in enumerate(ws.next_actions, start=1):
        lines += [
            f"### Action {i}",
            "",
            action,
            "",
            "- [ ] Assigned to:",
            "- [ ] Target date:",
            "- [ ] Done:",
            "",
        ]
    lines += [
        "---",
        "",
        "_Generated by AEOS Evidence Pack — read-only._",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Index HTML renderer
# ---------------------------------------------------------------------------

_INDEX_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
    font-family: 'Courier New', Courier, monospace;
    background: #0d1117;
    color: #c9d1d9;
    padding: 40px;
    font-size: 13px;
    line-height: 1.7;
    max-width: 760px;
    margin: 0 auto;
}
h1 { color: #58a6ff; font-size: 20px; margin-bottom: 4px; }
h2 {
    color: #8b949e;
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.12em;
    margin: 28px 0 10px;
    padding-bottom: 5px;
    border-bottom: 1px solid #21262d;
}
.meta { color: #6e7681; font-size: 11px; margin-bottom: 14px; }
.badge {
    display: inline-block;
    font-size: 10px;
    padding: 2px 7px;
    border-radius: 3px;
    margin-right: 6px;
    font-weight: bold;
}
.badge-ro  { background: #0c2a1e; color: #3fb950; border: 1px solid #196c3a; }
.badge-app { background: #2a0c0c; color: #f85149; border: 1px solid #6c1919; }
.badge-hum { background: #2a1e0c; color: #d29922; border: 1px solid #6c4a19; }
.verdict {
    display: inline-block;
    font-weight: bold;
    font-size: 15px;
    padding: 8px 16px;
    border-radius: 4px;
    margin: 12px 0;
}
.verdict-not-ready {
    background: #2a0c0c;
    color: #f85149;
    border: 2px solid #6c1919;
}
.verdict-ready {
    background: #0c2a1e;
    color: #3fb950;
    border: 2px solid #196c3a;
}
.file-list { list-style: none; margin-top: 8px; }
.file-list li {
    padding: 7px 0;
    border-bottom: 1px solid #21262d;
}
.file-list li:last-child { border-bottom: none; }
.file-list a { color: #58a6ff; text-decoration: none; }
.file-list a:hover { text-decoration: underline; }
.file-desc { color: #6e7681; margin-left: 8px; font-size: 11px; }
.kv { display: flex; flex-wrap: wrap; gap: 20px; margin: 12px 0; }
.kv-item { display: flex; flex-direction: column; }
.kv-lbl {
    font-size: 9px;
    color: #6e7681;
    text-transform: uppercase;
    letter-spacing: 0.08em;
}
.kv-val { font-size: 15px; font-weight: bold; }
.s-error { color: #f85149; }
.s-ok    { color: #3fb950; }
footer {
    margin-top: 40px;
    padding-top: 12px;
    border-top: 1px solid #21262d;
    font-size: 10px;
    color: #6e7681;
}
"""

_FILE_ENTRIES = [
    (
        "dashboard.html",
        "Technical audit timeline — all records, deltas, synthesis trends",
    ),
    (
        "project-workspace.html",
        "Executive project workspace — verdict, gates, risk register",
    ),
    (
        "recovery-summary.md",
        "Narrative recovery summary — baseline vs current, production status",
    ),
    (
        "risk-register.md",
        "Risk register — categorised findings with severity and action notes",
    ),
    (
        "human-gates.md",
        "Human validation gates — sign-off checklist before production",
    ),
    (
        "next-actions.md",
        "Next recommended actions — ordered with assignment fields",
    ),
]


def render_index(ws: WorkspaceData) -> str:
    """Return index.html as a string."""
    project = escape(ws.project_name)
    p = ws.recovery_progress
    pr = ws.production_readiness
    last = ws.records[-1]

    v_cls = "verdict-not-ready" if not pr.ready else "verdict-ready"
    critical = last.findings_summary.get("critical", 0)
    important = last.findings_summary.get("important", 0)

    c_cls = "s-error" if critical > 0 else "s-ok"
    i_cls = "s-error" if important > 20 else "s-ok"

    kv_html = (
        "<div class='kv'>"
        f"<div class='kv-item'><span class='kv-lbl'>Records</span>"
        f"<span class='kv-val'>{p.record_count}</span></div>"
        f"<div class='kv-item'><span class='kv-lbl'>Period</span>"
        f"<span class='kv-val'>{escape(p.first_date)} → "
        f"{escape(p.last_date)}</span></div>"
        f"<div class='kv-item'><span class='kv-lbl'>Critical</span>"
        f"<span class='kv-val {c_cls}'>{critical}</span></div>"
        f"<div class='kv-item'><span class='kv-lbl'>Important</span>"
        f"<span class='kv-val {i_cls}'>{important}</span></div>"
        "</div>"
    )

    file_items = "".join(
        f"<li><a href='{fname}'>{escape(fname)}</a>"
        f"<span class='file-desc'>— {escape(desc)}</span></li>"
        for fname, desc in _FILE_ENTRIES
    )

    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>AEOS Evidence Pack — {project}</title>\n"
        f"<style>{_INDEX_CSS}</style>\n"
        "</head>\n"
        "<body>\n"
        "<header>\n"
        "<h1>AEOS Evidence Pack</h1>\n"
        f"<div class='meta'>{project}</div>\n"
        "<div style='margin-top:8px'>\n"
        "<span class='badge badge-ro'>read_only: true</span>\n"
        "<span class='badge badge-app'>applied: false</span>\n"
        "<span class='badge badge-hum'>human validation required</span>\n"
        "</div>\n"
        "</header>\n"
        "<h2>Production Verdict</h2>\n"
        f"<div class='verdict {v_cls}'>{escape(pr.verdict)}</div>\n"
        "<h2>Project Metrics</h2>\n"
        f"{kv_html}\n"
        "<h2>Pack Contents</h2>\n"
        f"<ul class='file-list'>{file_items}</ul>\n"
        "<footer>\n"
        f"AEOS Evidence Pack · {project}"
        f" · {p.record_count} audit record(s)"
        f" · {escape(p.last_date)}"
        " · read_only: true · applied: false · human validation required\n"
        "</footer>\n"
        "</body>\n"
        "</html>"
    )


# ---------------------------------------------------------------------------
# Pack generator
# ---------------------------------------------------------------------------


def generate_evidence_pack(
    memory_dir: Path,
    project_name: str,
    output_dir: Path,
    overwrite: bool = False,
) -> EvidencePackResult:
    """Generate all evidence pack files into output_dir.

    Raises FileNotFoundError if memory_dir doesn't exist.
    Raises ValueError if no records found or output_dir is non-empty
    without --overwrite.
    """
    if output_dir.exists() and any(output_dir.iterdir()) and not overwrite:
        raise ValueError(
            f"'{output_dir}' already exists and is not empty."
            " Use --overwrite to replace it."
        )

    dash_data: DashboardData = load_dashboard_data(memory_dir, project_name)
    ws_data: WorkspaceData = load_workspace_data(memory_dir, project_name)

    output_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    def _write(name: str, content: str) -> Path:
        p = output_dir / name
        p.write_text(content, encoding="utf-8")
        written.append(p)
        return p

    _write("dashboard.html", render_dashboard(dash_data))
    _write("project-workspace.html", render_workspace(ws_data))
    _write("recovery-summary.md", render_recovery_summary(ws_data))
    _write("risk-register.md", render_risk_register(ws_data))
    _write("human-gates.md", render_human_gates(ws_data))
    _write("next-actions.md", render_next_actions(ws_data))
    _write("index.html", render_index(ws_data))

    return EvidencePackResult(
        output_dir=output_dir,
        project_name=project_name,
        record_count=len(ws_data.records),
        verdict=ws_data.production_readiness.verdict,
        files=written,
    )
